# Generated by Django 6.0.6 on 2026-06-10 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='disponibilites',
            field=models.CharField(blank=True, help_text='Ex: En soirée après 18h, le week-end...', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='format_preference',
            field=models.CharField(choices=[('PRESENTIEL', 'Présentiel uniquement'), ('EN_LIGNE', 'En ligne uniquement'), ('LES_DEUX', 'Présentiel et En ligne')], default='LES_DEUX', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text="Courte présentation et centres d'intérêt académiques"),
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_annonce', models.CharField(choices=[('OFFRE', 'Offre de Mentorat (Je propose mon aide / Mentor)'), ('DEMANDE', "Demande de Mentorat (Je cherche de l'aide / Apprenant)")], max_length=10)),
                ('matiere', models.CharField(help_text='Ex: Langage C, Administration Windows, Probabilités', max_length=100)),
                ('disponibilites', models.CharField(help_text='Ex: Les week-ends, Soirs après 18h', max_length=255)),
                ('format_cours', models.CharField(choices=[('PRESENTIEL', 'Présentiel'), ('EN_LIGNE', 'En ligne'), ('LES_DEUX', 'Présentiel et En ligne')], default='LES_DEUX', max_length=15)),
                ('description', models.TextField(blank=True, help_text='Précisez votre besoin ou vos compétences particulières...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='core.profile')),
            ],
        ),
    ]
