# Generated by Django 6.0.6 on 2026-06-10 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_avatar_url_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_skills', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='mentorskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_skills', to='core.profile'),
        ),
    ]
